"""Initial schema — all tables from the Phase 0 data model.

Revision ID: 0001
Revises:
Create Date: 2026-07-31

Written by hand rather than autogenerated, because the three things that matter
most here cannot be produced by autogenerate:

* the append-only triggers on `alerts` and `decisions`,
* the partial unique indexes that make "one live decision per alert" and "one
  equity baseline per trading day" database guarantees rather than application
  promises,
* the CHECK constraint pinning every broker account to testnet (constraint #2).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Money and quantities: NUMERIC(36, 18) everywhere. Never float (constraint #3).
MONEY = sa.Numeric(36, 18)
# Percentages stored as fractions: 0.01 == 1%.
PERCENT = sa.Numeric(9, 6)

UUID = postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    # ---------------------------------------------------------------- users --
    op.create_table(
        "users",
        sa.Column("id", UUID, nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    # ------------------------------------------------------------- sessions --
    op.create_table(
        "sessions",
        sa.Column("id", UUID, nullable=False),
        sa.Column("user_id", UUID, nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_sessions"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_sessions_user_id_users",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("token_hash", name="uq_sessions_token_hash"),
    )
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"])

    # ---------------------------------------------------- webhook_endpoints --
    op.create_table(
        "webhook_endpoints",
        sa.Column("id", UUID, nullable=False),
        sa.Column("user_id", UUID, nullable=False),
        # SHA-256 over (pepper || token). Deterministic so it can be indexed and
        # looked up on every request; peppered so a stolen database alone cannot
        # be brute-forced offline.
        sa.Column("endpoint_id_hash", sa.Text(), nullable=False),
        sa.Column("hmac_secret_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("hmac_secret_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("body_secret_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("body_secret_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_webhook_endpoints"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_webhook_endpoints_user_id_users",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "endpoint_id_hash", name="uq_webhook_endpoints_endpoint_id_hash"
        ),
    )
    op.create_index("ix_webhook_endpoints_user_id", "webhook_endpoints", ["user_id"])

    # ------------------------------------------------------ broker_accounts --
    op.create_table(
        "broker_accounts",
        sa.Column("id", UUID, nullable=False),
        sa.Column("user_id", UUID, nullable=False),
        sa.Column("broker", sa.String(64), nullable=False),
        sa.Column("label", sa.String(64), nullable=False),
        sa.Column("encrypted_credentials", sa.LargeBinary(), nullable=False),
        sa.Column("credentials_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("is_testnet", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "trading_state", sa.String(16), nullable=False, server_default="ACTIVE"
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_broker_accounts"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_broker_accounts_user_id_users",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("user_id", "label", name="uq_broker_accounts_user_id_label"),
        # Constraint #2 in the schema itself: until a later phase relaxes this,
        # Postgres physically refuses to store a live-trading account.
        sa.CheckConstraint("is_testnet = true", name="ck_broker_accounts_testnet_only"),
        sa.CheckConstraint(
            "trading_state IN ('ACTIVE', 'LOCKED')",
            name="ck_broker_accounts_trading_state_valid",
        ),
    )
    op.create_index("ix_broker_accounts_user_id", "broker_accounts", ["user_id"])

    # -------------------------------------------------------- risk_profiles --
    op.create_table(
        "risk_profiles",
        sa.Column("id", UUID, nullable=False),
        sa.Column("user_id", UUID, nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        # Rule 3
        sa.Column("max_alert_age_sec", sa.Integer(), nullable=False, server_default="30"),
        sa.Column(
            "future_tolerance_sec", sa.Integer(), nullable=False, server_default="5"
        ),
        # Rule 4
        sa.Column("dedupe_window_sec", sa.Integer(), nullable=False, server_default="60"),
        # Rule 5 — empty means nothing is tradeable; the default is deny.
        sa.Column(
            "allowed_symbols",
            postgresql.ARRAY(sa.String(32)),
            nullable=False,
            server_default=sa.text("'{}'::character varying[]"),
        ),
        # Rule 6
        sa.Column(
            "min_stop_distance_pct", PERCENT, nullable=False, server_default="0.001"
        ),
        # Rule 7
        sa.Column(
            "consecutive_loss_threshold", sa.Integer(), nullable=False, server_default="3"
        ),
        sa.Column(
            "circuit_breaker_cooldown_minutes", sa.Integer(), nullable=False,
            server_default="60",
        ),
        sa.Column(
            "circuit_breaker_manual_reset", sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ),
        # Rule 8
        sa.Column("max_daily_dd_pct", PERCENT, nullable=False, server_default="0.05"),
        # Rule 9
        sa.Column("risk_per_trade_pct", PERCENT, nullable=False, server_default="0.01"),
        sa.Column(
            "fee_slippage_buffer_bps", sa.Integer(), nullable=False, server_default="20"
        ),
        sa.Column(
            "max_notional_per_trade", MONEY, nullable=False, server_default="1000"
        ),
        # Rule 10
        sa.Column("max_open_positions", sa.Integer(), nullable=False, server_default="3"),
        sa.Column("max_total_notional", MONEY, nullable=False, server_default="5000"),
        sa.Column(
            "allow_pyramiding", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        # Daily reset: local wall-clock time + IANA zone name, never a UTC offset
        # (an offset drifts by an hour at every DST change).
        sa.Column(
            "daily_reset_time", sa.Time(), nullable=False, server_default="00:00:00"
        ),
        sa.Column("timezone", sa.String(64), nullable=False, server_default="UTC"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_risk_profiles"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_risk_profiles_user_id_users",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("user_id", name="uq_risk_profiles_user_id"),
        # A profile with risk_per_trade_pct = 50 (someone typing "50" meaning
        # 50%) would size positions 5,000x too large. This is the last place
        # that mistake can be caught before it reaches the sizing formula.
        sa.CheckConstraint(
            "risk_per_trade_pct > 0 AND risk_per_trade_pct < 1",
            name="ck_risk_profiles_risk_pct_fraction",
        ),
        sa.CheckConstraint(
            "max_daily_dd_pct > 0 AND max_daily_dd_pct < 1",
            name="ck_risk_profiles_dd_pct_fraction",
        ),
        sa.CheckConstraint(
            "min_stop_distance_pct > 0 AND min_stop_distance_pct < 1",
            name="ck_risk_profiles_stop_dist_pct_fraction",
        ),
        sa.CheckConstraint(
            "max_alert_age_sec > 0", name="ck_risk_profiles_alert_age_positive"
        ),
        sa.CheckConstraint(
            "future_tolerance_sec >= 0",
            name="ck_risk_profiles_future_tolerance_non_negative",
        ),
        sa.CheckConstraint(
            "dedupe_window_sec > 0", name="ck_risk_profiles_dedupe_window_positive"
        ),
        sa.CheckConstraint(
            "consecutive_loss_threshold > 0",
            name="ck_risk_profiles_loss_threshold_positive",
        ),
        sa.CheckConstraint(
            "circuit_breaker_cooldown_minutes >= 0",
            name="ck_risk_profiles_cooldown_non_negative",
        ),
        sa.CheckConstraint(
            "max_open_positions > 0", name="ck_risk_profiles_max_open_positive"
        ),
        sa.CheckConstraint(
            "max_notional_per_trade > 0",
            name="ck_risk_profiles_max_notional_trade_positive",
        ),
        sa.CheckConstraint(
            "max_total_notional > 0",
            name="ck_risk_profiles_max_total_notional_positive",
        ),
        sa.CheckConstraint(
            "fee_slippage_buffer_bps >= 0", name="ck_risk_profiles_buffer_non_negative"
        ),
    )

    # ---------------------------------------------------------- instruments --
    op.create_table(
        "instruments",
        sa.Column("broker", sa.String(64), nullable=False),
        sa.Column("symbol", sa.String(32), nullable=False),
        sa.Column("base_asset", sa.String(16), nullable=False),
        sa.Column("quote_asset", sa.String(16), nullable=False),
        sa.Column("tick_size", MONEY, nullable=False),
        sa.Column("lot_step", MONEY, nullable=False),
        sa.Column("min_qty", MONEY, nullable=False),
        sa.Column("min_notional", MONEY, nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        # Drives the staleness policy: past the maximum age we reject rather
        # than size against filters that may have changed.
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("broker", "symbol", name="pk_instruments"),
    )

    # --------------------------------------------------------------- alerts --
    op.create_table(
        "alerts",
        sa.Column("id", UUID, nullable=False),
        sa.Column("user_id", UUID, nullable=False),
        sa.Column("webhook_endpoint_id", UUID, nullable=False),
        # Payload as received, except the body `secret`, which is redacted
        # before storage (plan §4, OQ-4).
        sa.Column("raw_payload", postgresql.JSONB(), nullable=False),
        # SHA-256 of the true bytes, preserving what redaction costs: the
        # ability to prove what was actually received.
        sa.Column("raw_body_sha256", sa.LargeBinary(32), nullable=False),
        sa.Column("content_length", sa.Integer(), nullable=False),
        sa.Column("source_ip", postgresql.INET(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dedupe_key", sa.String(128), nullable=False),
        sa.Column("parse_status", sa.String(32), nullable=False),
        sa.Column("auth_mode", sa.String(16), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_alerts"),
        # RESTRICT, not CASCADE: deleting a user must never silently delete the
        # audit trail of what they traded.
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_alerts_user_id_users",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["webhook_endpoint_id"], ["webhook_endpoints.id"],
            name="fk_alerts_webhook_endpoint_id_webhook_endpoints",
            ondelete="RESTRICT",
        ),
    )
    op.create_index(
        "ix_alerts_dedupe_key_received_at", "alerts", ["dedupe_key", "received_at"]
    )
    op.create_index("ix_alerts_user_id_received_at", "alerts", ["user_id", "received_at"])

    # ------------------------------------------------------------ decisions --
    op.create_table(
        "decisions",
        sa.Column("id", UUID, nullable=False),
        sa.Column("alert_id", UUID, nullable=False),
        sa.Column("broker_account_id", UUID, nullable=True),
        sa.Column("verdict", sa.String(16), nullable=False),
        sa.Column("reason_code", sa.String(32), nullable=False),
        sa.Column("reason_detail", sa.Text(), nullable=True),
        # The config as it stood at evaluation time — what makes a later profile
        # edit unable to rewrite history.
        sa.Column("rule_snapshot", postgresql.JSONB(), nullable=False),
        sa.Column("risk_profile_version", sa.Integer(), nullable=False),
        sa.Column("computed_qty", MONEY, nullable=True),
        sa.Column("entry_reference_price", MONEY, nullable=True),
        sa.Column("stop_price", MONEY, nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "is_test", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.PrimaryKeyConstraint("id", name="pk_decisions"),
        sa.ForeignKeyConstraint(
            ["alert_id"], ["alerts.id"], name="fk_decisions_alert_id_alerts",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["broker_account_id"], ["broker_accounts.id"],
            name="fk_decisions_broker_account_id_broker_accounts",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "verdict IN ('APPROVED', 'REJECTED')", name="ck_decisions_verdict_valid"
        ),
    )
    # One alert produces exactly one real decision — enforced by the database,
    # so even two workers racing on the same alert cannot both insert. /test
    # decisions are excluded, since re-testing a signal is that endpoint's job.
    op.create_index(
        "uq_decisions_alert_id_live",
        "decisions",
        ["alert_id"],
        unique=True,
        postgresql_where=sa.text("is_test = false"),
    )
    op.create_index(
        "ix_decisions_reason_code_evaluated_at",
        "decisions",
        ["reason_code", "evaluated_at"],
    )

    # --------------------------------------------------------------- orders --
    op.create_table(
        "orders",
        sa.Column("id", UUID, nullable=False),
        sa.Column("decision_id", UUID, nullable=False),
        sa.Column("broker_account_id", UUID, nullable=False),
        # Ours, written before the HTTP call, passed to the exchange so a retry
        # can never become two orders.
        sa.Column("client_order_id", sa.String(64), nullable=False),
        sa.Column("broker_order_id", sa.String(64), nullable=True),
        sa.Column("symbol", sa.String(32), nullable=False),
        sa.Column("side", sa.String(8), nullable=False),
        sa.Column("type", sa.String(16), nullable=False),
        sa.Column("role", sa.String(16), nullable=False),
        sa.Column("qty", MONEY, nullable=False),
        sa.Column("price", MONEY, nullable=True),
        sa.Column("stop_price", MONEY, nullable=True),
        sa.Column("status", sa.String(24), nullable=False),
        sa.Column("filled_qty", MONEY, nullable=False, server_default="0"),
        sa.Column("avg_fill_price", MONEY, nullable=True),
        sa.Column("fees", MONEY, nullable=False, server_default="0"),
        sa.Column("fee_asset", sa.String(16), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        # A mapped internal error code, never raw broker exception text.
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_orders"),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["decisions.id"], name="fk_orders_decision_id_decisions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["broker_account_id"], ["broker_accounts.id"],
            name="fk_orders_broker_account_id_broker_accounts",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "broker_account_id", "client_order_id",
            name="uq_orders_broker_account_id_client_order_id",
        ),
    )
    op.create_index("ix_orders_decision_id", "orders", ["decision_id"])
    op.create_index("ix_orders_broker_order_id", "orders", ["broker_order_id"])
    op.create_index(
        "ix_orders_broker_account_id_status", "orders", ["broker_account_id", "status"]
    )

    # ------------------------------------------------------------ positions --
    op.create_table(
        "positions",
        sa.Column("id", UUID, nullable=False),
        sa.Column("broker_account_id", UUID, nullable=False),
        sa.Column("symbol", sa.String(32), nullable=False),
        sa.Column("qty", MONEY, nullable=False),
        sa.Column("avg_entry", MONEY, nullable=False),
        sa.Column("mark_price", MONEY, nullable=True),
        sa.Column("unrealized_pnl", MONEY, nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_positions"),
        sa.ForeignKeyConstraint(
            ["broker_account_id"], ["broker_accounts.id"],
            name="fk_positions_broker_account_id_broker_accounts",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "broker_account_id", "symbol", name="uq_positions_broker_account_id_symbol"
        ),
    )

    # ---------------------------------------------------- equity_snapshots ---
    op.create_table(
        "equity_snapshots",
        sa.Column("id", UUID, nullable=False),
        sa.Column("broker_account_id", UUID, nullable=False),
        # Mark-to-market: cash + holdings. What drawdown and sizing measure
        # against (plan §3, Q3).
        sa.Column("equity", MONEY, nullable=False),
        # Spendable cash: the hard affordability ceiling.
        sa.Column("free_balance", MONEY, nullable=True),
        sa.Column("position_value", MONEY, nullable=True),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "is_session_baseline", sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ),
        # The user-LOCAL trading day. Local, not UTC: the reset fires at the
        # user's wall-clock time in their own zone.
        sa.Column("session_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_equity_snapshots"),
        sa.ForeignKeyConstraint(
            ["broker_account_id"], ["broker_accounts.id"],
            name="fk_equity_snapshots_broker_account_id_broker_accounts",
            ondelete="CASCADE",
        ),
    )
    # Exactly one baseline per account per trading day. This is what makes the
    # restart and DST requirements hold structurally: a restart cannot mint a
    # second baseline, and a 23- or 25-hour DST day is still one session_date.
    op.create_index(
        "uq_equity_snapshots_baseline_per_day",
        "equity_snapshots",
        ["broker_account_id", "session_date"],
        unique=True,
        postgresql_where=sa.text("is_session_baseline = true"),
    )
    op.create_index(
        "ix_equity_snapshots_account_taken_at",
        "equity_snapshots",
        ["broker_account_id", "taken_at"],
    )

    # --------------------------------------------------------------- trades --
    op.create_table(
        "trades",
        sa.Column("id", UUID, nullable=False),
        sa.Column("broker_account_id", UUID, nullable=False),
        sa.Column("symbol", sa.String(32), nullable=False),
        sa.Column("side", sa.String(8), nullable=False),
        sa.Column("qty", MONEY, nullable=False),
        sa.Column("entry_price", MONEY, nullable=False),
        sa.Column("exit_price", MONEY, nullable=False),
        # Net of fees: a gross-positive, fee-negative trade is a loss, and the
        # circuit breaker must count it as one.
        sa.Column("realized_pnl", MONEY, nullable=False),
        sa.Column("fees", MONEY, nullable=False, server_default="0"),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entry_order_id", UUID, nullable=True),
        sa.Column("exit_order_id", UUID, nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_trades"),
        sa.ForeignKeyConstraint(
            ["broker_account_id"], ["broker_accounts.id"],
            name="fk_trades_broker_account_id_broker_accounts",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entry_order_id"], ["orders.id"], name="fk_trades_entry_order_id_orders",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["exit_order_id"], ["orders.id"], name="fk_trades_exit_order_id_orders",
            ondelete="SET NULL",
        ),
    )
    # Exactly the circuit breaker's query: most recent closed trades first.
    op.create_index(
        "ix_trades_account_closed_at", "trades", ["broker_account_id", "closed_at"]
    )

    # ------------------------------------------------ circuit_breaker_state --
    op.create_table(
        "circuit_breaker_state",
        sa.Column("broker_account_id", UUID, nullable=False),
        sa.Column("state", sa.String(16), nullable=False, server_default="CLOSED"),
        sa.Column(
            "consecutive_losses", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        # Null while OPEN means manual reset only.
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=True),
        # Makes recounting idempotent: a restart cannot double-count a loss.
        sa.Column("last_counted_trade_id", UUID, nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("broker_account_id", name="pk_circuit_breaker_state"),
        sa.ForeignKeyConstraint(
            ["broker_account_id"], ["broker_accounts.id"],
            name="fk_circuit_breaker_state_broker_account_id_broker_accounts",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["last_counted_trade_id"], ["trades.id"],
            name="fk_circuit_breaker_state_last_counted_trade_id_trades",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "state IN ('CLOSED', 'OPEN')",
            name="ck_circuit_breaker_state_circuit_state_valid",
        ),
        sa.CheckConstraint(
            "consecutive_losses >= 0",
            name="ck_circuit_breaker_state_losses_non_negative",
        ),
    )

    # ------------------------------------------- append-only enforcement -----
    # CLAUDE.md §6: alerts and decisions are append-only — never UPDATE, never
    # DELETE. A code review can enforce that on the day it is written; a trigger
    # enforces it forever, including against a future agent, a migration script,
    # and someone at a psql prompt at 3am.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION signalguard_forbid_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                '% is append-only: % is not permitted (SignalGuard audit trail)',
                TG_TABLE_NAME, TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("alerts", "decisions"):
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION signalguard_forbid_mutation();
            """
        )


def downgrade() -> None:
    for table in ("decisions", "alerts"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table};")
    op.execute("DROP FUNCTION IF EXISTS signalguard_forbid_mutation();")

    # Reverse creation order, so foreign keys never block a drop.
    op.drop_table("circuit_breaker_state")
    op.drop_table("trades")
    op.drop_table("equity_snapshots")
    op.drop_table("positions")
    op.drop_table("orders")
    op.drop_table("decisions")
    op.drop_table("alerts")
    op.drop_table("instruments")
    op.drop_table("risk_profiles")
    op.drop_table("broker_accounts")
    op.drop_table("webhook_endpoints")
    op.drop_table("sessions")
    op.drop_table("users")
