"""Order submission and protective-stop placement (CLAUDE.md §10).

The rule this module exists to enforce: **never leave a naked position.**

Binance spot has no true bracket order, so an entry and its stop are two
requests. Between them there is a window where the position exists with no
protection. If stop placement fails in that window, the only safe action is to
close the position immediately and alert loudly — leaving it open and hoping is
how a small loss becomes an account-ending one overnight.

That is deliberately a *worse trading outcome* (an unwanted round-trip and its
fees) in exchange for a *bounded risk outcome*. This project makes that trade
every time.
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal

from sqlalchemy.ext.asyncio import AsyncSession

from signalguard.db.models import Order as OrderRow
from signalguard.enums import OrderRole, OrderSide, OrderStatus, OrderType
from signalguard.execution.base import (
    BrokerAdapter,
    BrokerError,
    BrokerOrder,
    OrderRequest,
)
from signalguard.notify import Notifier

logger = logging.getLogger(__name__)


def new_client_order_id() -> str:
    """A unique, exchange-safe client order ID.

    Generated by us before submission and passed to the exchange, so a retried
    request is recognised as the same order rather than becoming a second one.
    Binance allows up to 36 characters for spot client order IDs.
    """
    return f"sg{uuid.uuid4().hex[:30]}"


@dataclass(frozen=True)
class ExecutionResult:
    entry: BrokerOrder | None
    stop: BrokerOrder | None
    naked_position_closed: bool = False
    error: str | None = None

    @property
    def is_protected(self) -> bool:
        return self.entry is not None and self.stop is not None


async def record_order(
    session: AsyncSession,
    *,
    decision_id: uuid.UUID,
    broker_account_id: uuid.UUID,
    client_order_id: str,
    request: OrderRequest,
    role: OrderRole,
) -> OrderRow:
    """Write the order row BEFORE the network call.

    This ordering is the whole reason a lost response is survivable: whatever
    happens next, we know what we sent and under which client ID, so
    reconciliation can ask the broker about it. Writing the row afterwards would
    mean a timeout leaves an order at the exchange we have no record of.
    """
    row = OrderRow(
        id=uuid.uuid4(),
        decision_id=decision_id,
        broker_account_id=broker_account_id,
        client_order_id=client_order_id,
        symbol=request.symbol,
        side=request.side.value,
        type=request.order_type.value,
        role=role.value,
        qty=request.qty,
        price=request.price,
        stop_price=request.stop_price,
        status=OrderStatus.PENDING_SUBMIT.value,
        filled_qty=Decimal("0"),
        fees=Decimal("0"),
    )
    session.add(row)
    await session.flush()
    return row


def apply_broker_result(row: OrderRow, result: BrokerOrder) -> None:
    row.broker_order_id = result.broker_order_id
    row.status = result.status.value
    row.filled_qty = result.filled_qty
    row.avg_fill_price = result.avg_fill_price
    row.fees = result.fees
    row.fee_asset = result.fee_asset
    row.submitted_at = result.submitted_at or datetime.now(UTC)


async def submit_entry_with_stop(
    session: AsyncSession,
    broker: BrokerAdapter,
    *,
    decision_id: uuid.UUID,
    broker_account_id: uuid.UUID,
    symbol: str,
    side: OrderSide,
    order_type: OrderType,
    qty: Decimal,
    limit_price: Decimal | None,
    stop_price: Decimal,
    notifier: Notifier | None = None,
    account_label: str = "account",
) -> ExecutionResult:
    """Submit an entry and its protective stop, or leave nothing behind.

    `notifier` is optional and best-effort. It exists for one message in
    particular: a position that could not be protected. A CRITICAL log line is
    the right permanent record, but nobody is reading logs at 3am — §10 says
    alert **loudly**, and that means pushing, not writing.
    """
    entry_request = OrderRequest(
        client_order_id=new_client_order_id(),
        symbol=symbol,
        side=side,
        order_type=order_type,
        qty=qty,
        price=limit_price,
    )
    entry_row = await record_order(
        session,
        decision_id=decision_id,
        broker_account_id=broker_account_id,
        client_order_id=entry_request.client_order_id,
        request=entry_request,
        role=OrderRole.ENTRY,
    )

    try:
        entry = await broker.submit_order(entry_request)
    except BrokerError as exc:
        # No position was opened, so there is nothing to protect or unwind.
        entry_row.status = OrderStatus.REJECTED.value
        entry_row.last_error = exc.code.value
        await session.flush()
        logger.error(
            "Entry order rejected",
            extra={"symbol": symbol, "error_code": exc.code.value},
        )
        return ExecutionResult(entry=None, stop=None, error=exc.code.value)

    apply_broker_result(entry_row, entry)
    await session.flush()

    # The position now exists and is unprotected. Everything below runs against
    # the clock.
    exit_side = OrderSide.SELL if side is OrderSide.BUY else OrderSide.BUY
    protected_qty = entry.filled_qty if entry.filled_qty > 0 else entry.qty

    stop_request = OrderRequest(
        client_order_id=new_client_order_id(),
        symbol=symbol,
        side=exit_side,
        order_type=OrderType.MARKET,
        qty=protected_qty,
        stop_price=stop_price,
    )
    stop_row = await record_order(
        session,
        decision_id=decision_id,
        broker_account_id=broker_account_id,
        client_order_id=stop_request.client_order_id,
        request=stop_request,
        role=OrderRole.STOP,
    )

    try:
        stop = await broker.submit_order(stop_request)
    except BrokerError as exc:
        stop_row.status = OrderStatus.REJECTED.value
        stop_row.last_error = exc.code.value
        await session.flush()
        logger.critical(
            "Stop placement FAILED — closing the naked position immediately",
            extra={
                "symbol": symbol,
                "qty": str(protected_qty),
                "error_code": exc.code.value,
            },
        )
        closed = await _emergency_close(
            session,
            broker,
            decision_id=decision_id,
            broker_account_id=broker_account_id,
            symbol=symbol,
            side=exit_side,
            qty=protected_qty,
        )
        # Alert either way. A position we closed is a resolved incident the user
        # still needs to know about; one we could not close is the most urgent
        # thing this system can produce.
        if notifier is not None:
            await notifier.naked_position(account_label, symbol)
        return ExecutionResult(
            entry=entry, stop=None, naked_position_closed=closed,
            error=f"stop_failed:{exc.code.value}",
        )

    apply_broker_result(stop_row, stop)
    await session.flush()
    return ExecutionResult(entry=entry, stop=stop)


async def _emergency_close(
    session: AsyncSession,
    broker: BrokerAdapter,
    *,
    decision_id: uuid.UUID,
    broker_account_id: uuid.UUID,
    symbol: str,
    side: OrderSide,
    qty: Decimal,
) -> bool:
    """Flatten a position that could not be protected.

    If this *also* fails, we log at CRITICAL and return False. There is nothing
    further this code can do — but the operator must find out, because a naked
    position that we know about and could not close is the single most urgent
    thing that can happen in this system.
    """
    close_request = OrderRequest(
        client_order_id=new_client_order_id(),
        symbol=symbol,
        side=side,
        order_type=OrderType.MARKET,
        qty=qty,
    )
    close_row = await record_order(
        session,
        decision_id=decision_id,
        broker_account_id=broker_account_id,
        client_order_id=close_request.client_order_id,
        request=close_request,
        role=OrderRole.EXIT,
    )
    try:
        closed = await broker.submit_order(close_request)
    except BrokerError as exc:
        close_row.status = OrderStatus.REJECTED.value
        close_row.last_error = exc.code.value
        await session.flush()
        logger.critical(
            "NAKED POSITION — emergency close failed. Manual intervention required.",
            extra={
                "symbol": symbol,
                "qty": str(qty),
                "error_code": exc.code.value,
                "broker_account_id": str(broker_account_id),
            },
        )
        return False

    apply_broker_result(close_row, closed)
    await session.flush()
    logger.warning(
        "Naked position closed after stop placement failed",
        extra={"symbol": symbol, "qty": str(qty)},
    )
    return True
